In [1]:
! pip install numpy pandas

  Using cached numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 313.7 kB/s eta 0:00:0000:0100:02
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]


In [2]:
! pip install matplotlib

  Using cached contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 3.3 MB/s eta 0:00:00a 0:00:01
Using cached contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (355 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 1.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 874.5 kB/s eta 0:00:00a 0:00:01
Using cached pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]


In [4]:
! pip install --no-cache-dir transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 942.6 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.5/561.5 kB 857.7 kB/s eta 0:00:00:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 663.6 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 569.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.0/763.0 kB 382.5 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.9/798.9 kB 393.8 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [transformers] [transformers]ub]er]


In [10]:
! pip cache purge

Files removed: 0 (0 bytes)


In [5]:
! rm -rf ~/.cache/pip

In [6]:
! rm -rf ~/.conda ~/.cache

In [7]:
! pip uninstall -y torch torchvision torchaudio

In [11]:
! pip show torch

Name: torch
Version: 2.8.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: 


In [12]:
! pip install torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 10.5 MB/s eta 0:00:00 0:00:01


In [23]:
! pip install protobuf

In [3]:
! pip show soundfile

Name: soundfile
Version: 0.13.1
Summary: An audio library based on libsndfile, CFFI and NumPy
Home-page: https://github.com/bastibe/python-soundfile
Author: Bastian Bechtold
Author-email: basti@bastibe.de
License: BSD 3-Clause License
Location: /run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages
Requires: cffi, numpy
Required-by: librosa


In [14]:
! pip install --upgrade transformers

In [15]:
! df -h

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           7.5G  144K  7.5G   1% /etc/timezone
/dev/nvme1n1p3  476G   65G  410G  14% /usr
tmpfs           7.5G     0  7.5G   0% /usr/lib/x86_64-linux-gnu/GL
/dev/nvme1n1p3  476G   65G  410G  14% /home
tmpfs           1.5G   18M  1.5G   2% /run/host/monitor
devtmpfs        7.4G     0  7.4G   0% /dev
tmpfs           7.5G   31M  7.4G   1% /dev/shm
tmpfs           7.5G     0  7.5G   0% /home/aadimprajapati/.local/share/flatpak
tmpfs           7.5G     0  7.5G   0% /home/aadimprajapati/.var/app
tmpfs           3.0G  2.4M  3.0G   1% /run/media
/dev/nvme0n1p2  366G  207G  160G  57% /run/media/aadimprajapati/Volume(D)
tmpfs           7.5G     0  7.5G   0% /tmp/.X11-unix
tmpfs           7.5G   11M  7.5G   1% /tmp/.X11-unix/X0


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import transformers
import torchaudio
import os

/run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
print(os.path.exists("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac"))

True


In [5]:
torchaudio.set_audio_backend("soundfile")

try:
    waveform, sample_rate = torchaudio.load("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac")
    print("Loaded successfully:", waveform.shape, sample_rate)
except Exception as e:
    print("Error loading audio:", e)

Loaded successfully: torch.Size([1, 70400]) 16000


/tmp/ipykernel_1275/4219840875.py:1: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release. 
  torchaudio.set_audio_backend("soundfile")
/run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages/torchaudio/_internal/module_utils.py:71: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  return func(*args, **kwargs)
/run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages/torchaudio/_backend/utils.py:213: UserWarning: In 2.9, this function's implementation

In [6]:
import soundfile as sf

try:
    data, samplerate = sf.read("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac")
    print("SoundFile loaded:", data.shape, samplerate)
except Exception as e:
    print("SoundFile error:", e)

SoundFile loaded: (70400,) 16000


In [7]:
print(torchaudio.__version__)

2.8.0+cu128


In [8]:
try:
    waveform, sample_rate = torchaudio.load("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac")
    print("Loaded successfully:", waveform.shape, sample_rate)
except Exception as e:
    print("Error loading audio:", e)

Loaded successfully: torch.Size([1, 70400]) 16000


In [9]:
print(os.path.exists("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac"))
print(os.access("data/asr_nepali_0/asr_nepali/data/00/000a0be2c6.flac", os.R_OK))

True
True


In [10]:
df = pd.read_csv('data/asr_nepali_0/asr_nepali/utt_spk_text.tsv', sep='\t', names=['file', 'speaker', 'text'], header=None)

In [11]:
df

file speaker                  text
0       4aa1fdca33   6a6d1      ००७ मिलको दूरीमा
1       86e521554a   1f680      ००७ मिलको दूरीमा
2       c96b2b1afb   e349f      ००७ मिलको दूरीमा
3       2f7ab41953   294d8  ०११ देखि काङ्ग्रेसको
4       c290e5124b   88901      ०१ सौर द्रव्यमान
...            ...     ...                   ...
157900  17c05d0bdb   06372      ह्रास हुन लाग्दछ
157901  2aa4a03723   79c24      ह्रास हुन लाग्दछ
157902  4cb59eba81   99866      ह्रास हुन लाग्दछ
157903  223df784fc   e7c22           ह्रास हुँदै
157904  fc3b1054b0   95358       ह्वाइटआई भनिन्छ

[157905 rows x 3 columns]

In [13]:
for x in df['file'].head():
    parentdiv = f'data/asr_nepali_{x[0]}/asr_nepali/data/{x[:2]}'
    try:
        waveform, sample_rate = torchaudio.load(f"{parentdiv}/{x}.flac")
        print("Loaded successfully:", waveform.shape, sample_rate)
        print(waveform)
    except Exception as e:
        print("Error loading audio:", e)

Loaded successfully: torch.Size([1, 67200]) 16000
tensor([[ 1.3123e-03,  1.5259e-03,  7.6294e-04,  ...,  9.1553e-05,
          9.1553e-05, -5.4932e-04]])
Loaded successfully: torch.Size([1, 62400]) 16000
tensor([[-0.0013, -0.0018, -0.0019,  ...,  0.0013,  0.0005,  0.0006]])
Loaded successfully: torch.Size([1, 49600]) 16000
tensor([[-0.0024, -0.0012, -0.0025,  ..., -0.0002,  0.0012,  0.0015]])
Loaded successfully: torch.Size([1, 65600]) 16000
tensor([[-0.0025, -0.0007, -0.0015,  ..., -0.0257, -0.0190, -0.0113]])
Loaded successfully: torch.Size([1, 62400]) 16000
tensor([[-1.2207e-04, -1.2207e-04, -1.2207e-04,  ...,  3.0518e-04,
          9.1553e-05,  1.2207e-04]])


/run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages/torchaudio/_backend/utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(


In [17]:
from torch.utils.data import Dataset, DataLoader

In [15]:
class NepaliASRDataset(Dataset):
    def __init__(self, df, root="data"):
        self.df = df
        self.root = root
    
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        x = self.df.iloc[idx]
        parentdiv = f'{self.root}/asr_nepali_{x["file"][0]}/asr_nepali/data/{x["file"][:2]}'
        waveform, sample_rate = torchaudio.load(f"{parentdiv}/{x['file']}.flac")

        # resampling to 16kHz if not already
        if sample_rate != 16000:
            waveform = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=16000)(waveform)
            sample_rate = 16000
        return waveform, sample_rate, x['text']

In [ ]:
if waveform.ndim > 1:
    waveform = waveform[0]

In [ ]:
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import torch

In [ ]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/run/media/aadimprajapati/Volume(D)/fnclick/python/shruti2bhasa/env/lib/python3.11/site-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


In [ ]:
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
model.eval()

Wav2Vec2ForCTC(
  (wav2vec2): Wav2Vec2Model(
    (feature_extractor): Wav2Vec2FeatureEncoder(
      (conv_layers): ModuleList(
        (0): Wav2Vec2GroupNormConvLayer(
          (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,), bias=False)
          (activation): GELUActivation()
          (layer_norm): GroupNorm(512, 512, eps=1e-05, affine=True)
        )
        (1-4): 4 x Wav2Vec2NoLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,), bias=False)
          (activation): GELUActivation()
        )
        (5-6): 2 x Wav2Vec2NoLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,), bias=False)
          (activation): GELUActivation()
        )
      )
    )
    (feature_projection): Wav2Vec2FeatureProjection(
      (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (projection): Linear(in_features=512, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder)